---
title: "KW 1 KBB"
author: "Nathan Hawkins"
date: "9/14/2021"
output: html_document
---
```{r}
library(ggplot2)
library(bestglm)
library(corrplot)
```


#EDA
```{r}
kbb <- read.csv("KBB.csv", stringsAsFactors = TRUE)

ggplot(data = kbb, mapping = aes(x = Mileage, y = Price)) + 
  geom_point() 

ggplot(data = kbb, mapping = aes(x = as.factor(Doors), y = Price)) + 
  geom_boxplot() 

ggplot(data = kbb, mapping = aes(x = as.factor(Cylinder), y = Price)) + 
  geom_boxplot() 

ggplot(data = kbb, mapping = aes(x = as.factor(Make), y = Price)) + 
  geom_boxplot() 

ggplot(data = kbb, mapping = aes(y = as.factor(Trim), x = Price)) + 
  geom_boxplot() 

ggplot(data = kbb, mapping = aes(y = as.factor(Model), x = Price)) + 
  geom_boxplot() 

ggplot(data = kbb, mapping = aes(x = as.factor(Leather), y = Price)) + 
  geom_boxplot()

ggplot(data = kbb, mapping = aes(x = as.factor(Sound), y = Price)) + 
  geom_boxplot()

ggplot(data = kbb, mapping = aes(x = as.factor(Cruise), y = Price)) + 
  geom_boxplot()
```



```{r}
library(dplyr)


kbb$make_model_trim <- as.factor(paste0(kbb$Make, kbb$Model, kbb$Trim))

library(bestglm)
bestglm(kbb[,c(2:13,1)], IC = "AIC", method = "exhaustive")

model <- lm(Price ~  Mileage + Mileage:Make + Sound + Leather + make_model_trim , data = kbb)

AIC(model)
BIC(model)
rsq::rsq(model)
summary(model)
library(car)
vif(model)

sd(model$residuals)
sd(kbb$Price)

length(model$coefficients)

library(ggplot2)
ggplot(data = kbb, mapping = aes(x = Mileage, y = Price, )) + 
  geom_point()
```

```{r}
samp <- sample(1:nrow(kbb), round(nrow(kbb)*.9, 0), replace = FALSE)
train <- kbb[samp,]
test <- kbb[-samp,]

train.model <- lm(Price ~  Mileage + Mileage:Make + Sound + Leather + make_model_trim , data = train)

predictions <- predict.lm(train.model, test)

(test$Price - predictions)^2
```



```{r}

summary(model)
library(multcomp)
library(car)
car::vif(model)
a <- matrix(rep(0, 66), nrow = 1)
a[45] <- 1
dim(a)
library(MASS)
dim(vcov(model))
glht_a <- glht(model, a)
summary(glht_a)
```


```{r include = FALSE}
kbb$Cylinder <- as.factor(kbb$Cylinder)
model <- Price~.
fit <- lm(model, kbb)
test <- ols_step_all_possible(fit)
View(test)

```


# Assumptions

Linearity assumption.
```{r}
avPlots(model)
```

# Normality

They look very normal.
```{r}
hist(model$residuals)
qqPlot(model)
```
# Equal Variance

```{r}
plot(model$fitted.values, model$residuals)
plot(model)
```



```{r}
library(magrittr)
mydataset <- kbb
n <- round(nrow(mydataset),0)
n.cv <- 100 #Number of CV studies to run
n.test <-  round(nrow(mydataset)*0.1,0)
rpmse <- rep(x=NA, times=n.cv)
bias <- rep(x=NA, times=n.cv)
wid <- rep(x=NA, times=n.cv)
cvg <- rep(x=NA, times=n.cv)
for(cv in 1:n.cv){
  ## Select test observations
  test.obs <- sample(x=1:n, size=n.test)
  
  ## Split into test and training sets
  test.set <- mydataset[test.obs,]
  train.set <- mydataset[-test.obs,]
  
  ## Fit a lm() using the training data
  train.lm <- lm(Price ~  Mileage + Mileage:Make + Sound + Leather + make_model_trim , data = train.set)
  
  ## Generate predictions for the test set
  my.preds <- predict.lm(train.lm, newdata=test.set, interval="prediction")
  
  ## Calculate bias
  bias[cv] <- mean(my.preds[,'fit']-test.set[['Price']])
  
  ## Calculate RPMSE
  rpmse[cv] <- (test.set[['Price']]-my.preds[,'fit'])^2 %>% mean() %>% sqrt()
  
  ## Calculate Coverage
  cvg[cv] <- ((test.set[['Price']] > my.preds[,'lwr']) & (test.set[['Price']] < my.preds[,'upr'])) %>% mean()
  
  ## Calculate Width
  wid[cv] <- (my.preds[,'upr'] - my.preds[,'lwr']) %>% mean()
  
}
hist(rpmse)
hist(bias)
mean(bias)
hist(cvg)
hist(wid)
sd(kbb$Price)
```

